name: docker

on:
  push:
    branches: ["main"]
    tags:
      - v*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DOCKER_IMAGE_NAME: ghcr.io/sovanetwork/sova-bitcoin-sync
  DOCKER_USERNAME: ${{ github.actor }}

jobs:
  build:
    name: build and push
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: taiki-e/install-action@cross

      - name: Set version tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=unknown" >> $GITHUB_OUTPUT
        shell: bash

      - name: Log in to Docker
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username ${DOCKER_USERNAME} --password-stdin

      - name: Set up Docker builder
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install arm64,amd64
          docker buildx create --name cross-builder --use
          docker buildx inspect --bootstrap

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ steps.version.outputs.VERSION == 'latest' && format('{0}:latest', env.DOCKER_IMAGE_NAME) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max